language: python
python:
    - "2.7"
    - "3.4"
install:
    - "pip install ."
    - "pip install flake8"
    - "pip install lxml"
    - "pip install coveralls"
script:
    - "flake8 githubtrending"
    - "flake8 test"
    - "coverage run --source=githubtrending -m test.test_github_trending"
after_script:
    - coveralls